GET http://localhost:3000/users

###

GET http://localhost:3000/users/f1ab9893-3e4b-4a9c-a725-47dce6905b2d

###

POST http://localhost:3000/users
content-type: application/json

{
    "name": "Erick Reis",
    "email": "erick4@erick4.com",
    "password": "123456"
}

###

PUT http://localhost:3000/users/f1ab9893-3e4b-4a9c-a725-47dce6905b2d
content-type: application/json

{
    "id":"f1ab9893-3e4b-4a9c-a725-47dce6905b2d",
    "name": "Erick Machado",
    "email": "erick@machado.com"
}

###

DELETE http://localhost:3000/users/19fe49a5-69b9-4a8d-9b6c-6815408e664f

###

GET http://localhost:3000/posts

####

POST http://localhost:3000/posts
content-type: application/json

{
    "title": "Post 1",
    "content": "Content 1",
    "user_id": "f1ab9893-3e4b-4a9c-a725-47dce6905b2d"
}